# Generated by Django 4.1.4 on 2022-12-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMssg',
            fields=[
                ('img_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('open_date', models.DateTimeField()),
                ('cur_stat', models.CharField(max_length=200)),
            ],
        ),
    ]
