# Generated by Django 4.1.4 on 2022-12-08 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmssg',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sendmssg',
            name='open_date',
            field=models.CharField(max_length=200),
        ),
    ]
